// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:f097b7b1-0059-45d4-af91-cdea7ed4279b",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_gCXtuwiIl",
    "aws_user_pools_web_client_id": "4kri73cfjcqn1s7022e50slgfb"
};


export default awsmobile;
